/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package comnieu.ui.manager;

import comnieu.dao.PromotionDAO;
import comnieu.dao.impl.PromotionDAOImpl;
import comnieu.entity.Promotion;
import comnieu.util.TimeRange;
import comnieu.util.XDate;
import comnieu.util.XDialog;
import comnieu.util.XStr;
import java.math.BigDecimal;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.function.BiConsumer;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import lombok.Getter;
import lombok.Setter;
/**
 *
 * @author amyas
 */
public class PromotionManager extends javax.swing.JFrame {

    /**
     * Creates new form PromotionManager
     */
    public PromotionManager() {
    initComponents();
    fillToTable();
    Date now = new Date();
    txtBegin.setText(XDate.format(now, pattern));
    txtEnd.setText(XDate.format(now, pattern)); // Khởi tạo txtEnd với ngày hiện tại
    txtStartDate.setText(XDate.format(now, pattern));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPromotion = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnCheckall = new javax.swing.JButton();
        btnUncheckall = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBegin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();
        cboTimeRanges = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPromotion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã KM", "Tên KM", "Ngày bắt đầu", "Ngày kết thúc", "Giảm giá", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPromotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPromotionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPromotion);

        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnCheckall.setText("Chọn tất cả");
        btnCheckall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckallActionPerformed(evt);
            }
        });

        btnUncheckall.setText("Bỏ chọn tất cả");
        btnUncheckall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUncheckallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUncheckall)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckall)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnCheckall)
                    .addComponent(btnUncheckall))
                .addContainerGap())
        );

        tabs.addTab("Bảng", jPanel1);

        jLabel2.setText("Ngày bắt đầu");

        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên KM");

        jLabel4.setText("Ngày kết thúc");

        jLabel5.setText("Giảm giá");

        btnCreate.setText("Tạo mới");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Nhập mới");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel8.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addGap(365, 365, 365))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnCreate)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnUpdate)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDelete)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnClear))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(164, 164, 164))
                                            .addComponent(txtStartDate))
                                        .addComponent(jLabel8)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                        .addComponent(txtEndDate)))))
                        .addGap(0, 32, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiscount)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnCreate))
                .addGap(39, 39, 39))
        );

        tabs.addTab("Biểu mẫu", jPanel2);

        jLabel6.setText("Từ ngày: ");

        txtBegin.setColumns(8);

        jLabel7.setText("Đến ngày: ");

        txtEnd.setColumns(8);

        btnFilter.setText("Lọc");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        cboTimeRanges.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hôm nay", "Tuần này", "Tháng này", "Quý này", "Năm nay" }));
        cboTimeRanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTimeRangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(txtBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnFilter)
                .addGap(5, 5, 5)
                .addComponent(cboTimeRanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter)
                    .addComponent(cboTimeRanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.update();
    }                                         

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.clearForm();
    }                                        

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.filterByDateRange();
    }                                         

    private void cboTimeRangesActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        this.timeRangeSelected();
        if (timeChanged != null) {
            timeChanged.accept(getFrom(), getTo());
        }
    }                                             

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.create();
    }                                         

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.delete();
    }                                         

    private void tblPromotionMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.edit();
        }
    }                                         

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.deleteCheckedItems();
    }                                        

    private void btnCheckallActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        this.checkAll(rootPaneCheckingEnabled);
    }                                           

    private void btnUncheckallActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        this.UncheckAll(rootPaneCheckingEnabled);
    }                                             

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromotionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromotionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromotionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromotionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromotionManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCheckall;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnUncheckall;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboTimeRanges;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblPromotion;
    private javax.swing.JTextField txtBegin;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration                   

        private PromotionDAO dao = new PromotionDAOImpl();
    private List<Promotion> items = List.of();

    @Setter
    BiConsumer<Date, Date> timeChanged;

    @Getter
    @Setter
    String pattern = "dd/MM/yyyy";

    public Date getFrom() {
        return XDate.parse(txtBegin.getText(), pattern);
    }

    public void setFrom(Date from) {
        txtBegin.setText(XDate.format(from, pattern));
    }

    public Date getTo() {
        return XDate.parse(txtEnd.getText(), pattern);
    }

    public void setTo(Date to) {
        txtEnd.setText(XDate.format(to, pattern));
    }

    private void timeRangeSelected() {
        TimeRange range = TimeRange.today();
        switch (cboTimeRanges.getSelectedIndex()) {
            case 0 -> {
                range = TimeRange.today();
            }
            case 1 -> {
                range = TimeRange.thisWeek();
            }
            case 2 -> {
                range = TimeRange.thisMonth();
            }
            case 3 -> {
                range = TimeRange.thisQuarter();
            }
            case 4 -> {
                range = TimeRange.thisYear();
            }
        }
        this.setFrom(range.getBegin());
        this.setTo(range.getEnd());
    }

   public void fillToTable() {
    DefaultTableModel model = (DefaultTableModel) tblPromotion.getModel();
    model.setRowCount(0);
    items = dao.findAll();
    for (Promotion p : items) {
        Object[] row = {
            p.getId(),
            p.getName(),
            XDate.format(p.getStartDate(), Promotion.DATE_PATTERN),
            XDate.format(p.getEndDate(), Promotion.DATE_PATTERN),
            
            p.getDiscountRate().multiply(BigDecimal.valueOf(100)).stripTrailingZeros().toPlainString() + "%"
        };
        model.addRow(row);
    }
}
   
private void filterByDateRange() {
    DefaultTableModel model = (DefaultTableModel) tblPromotion.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    tblPromotion.setRowSorter(sorter);

    try {
        // Kiểm tra đầu vào
        String beginText = txtBegin.getText().trim();
        String endText = txtEnd.getText().trim();

        if (beginText.isEmpty() || endText.isEmpty()) {
            XDialog.alertError("Vui lòng nhập đầy đủ ngày bắt đầu và ngày kết thúc!");
            return;
        }

        // Kiểm tra định dạng ngày
        if (!isValidDateFormat(beginText, pattern) || !isValidDateFormat(endText, pattern)) {
            XDialog.alertError("Định dạng ngày không hợp lệ! Vui lòng nhập theo định dạng " + pattern);
            return;
        }

        Date fromDate = XDate.parse(beginText, pattern);
        Date toDate = XDate.parse(endText, pattern);

        if (fromDate == null || toDate == null) {
            XDialog.alertError("Không thể phân tích ngày! Vui lòng kiểm tra định dạng.");
            return;
        }

        if (fromDate.after(toDate)) {
            XDialog.alertError("Ngày bắt đầu phải trước ngày kết thúc!");
            return;
        }

        RowFilter<DefaultTableModel, Integer> filter = new RowFilter<DefaultTableModel, Integer>() {
            @Override
            public boolean include(Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                String startDateStr = (String) entry.getValue(2); // Cột 2: Ngày bắt đầu
                String endDateStr = (String) entry.getValue(3);   // Cột 3: Ngày kết thúc

                try {
                    Date startDate = XDate.parse(startDateStr, Promotion.DATE_PATTERN);
                    Date endDate = XDate.parse(endDateStr, Promotion.DATE_PATTERN);

                    // Bao gồm hàng nếu khoảng thời gian của khuyến mãi giao với khoảng thời gian lọc
                    return !startDate.after(toDate) && !endDate.before(fromDate);
                } catch (Exception e) {
                    e.printStackTrace();
                    return false;
                }
            }
        };

        sorter.setRowFilter(filter);
    } catch (Exception e) {
        e.printStackTrace();
        XDialog.alertError("Lỗi khi lọc dữ liệu: " + e.getMessage());
    }
}

// Phương thức hỗ trợ để kiểm tra định dạng ngày
private boolean isValidDateFormat(String dateStr, String pattern) {
    try {
        SimpleDateFormat sdf = new SimpleDateFormat(pattern);
        sdf.setLenient(false); // Phân tích nghiêm ngặt
        sdf.parse(dateStr);
        return true;
    } catch (Exception e) {
        return false;
    }
}
    public void setForm(Promotion entity) {
        txtId.setText(XStr.valueOf(entity.getId()));
        txtName.setText(XStr.valueOf(entity.getName()));
        txtStartDate.setText(XDate.format(entity.getStartDate(), Promotion.DATE_PATTERN));
        txtEndDate.setText(XDate.format(entity.getEndDate(), Promotion.DATE_PATTERN));
        txtDiscount.setText(String.valueOf(entity.getDiscountRate()));

    }

    public Promotion getForm() {
    try {
        Promotion entity = new Promotion();

        String idText = txtId.getText().trim();
        if (!idText.isEmpty()) {
            entity.setId(Integer.parseInt(idText));
        }

        entity.setName(txtName.getText().trim());

        entity.setStartDate(XDate.parse(txtStartDate.getText().trim(), Promotion.DATE_PATTERN));
        entity.setEndDate(XDate.parse(txtEndDate.getText().trim(), Promotion.DATE_PATTERN));

        String discountText = txtDiscount.getText().trim().replace("%", "");
        double discount = Double.parseDouble(discountText) / 100;

        
        entity.setDiscountRate(BigDecimal.valueOf(discount));

        return entity;
    } catch (NumberFormatException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Giá trị số không hợp lệ (ID hoặc phần trăm giảm giá).");
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi không xác định: " + ex.getMessage());
    }
    return null;
}

    public void create() {
        Promotion entity = this.getForm();
        dao.create(entity);
        XDialog.alertSuccess("Thêm thành công");
        this.fillToTable();
    }

    public void update() {
        Promotion entity = this.getForm();
        dao.update(entity);
        XDialog.alertSuccess("Cập nhật thành công");
        this.fillToTable();
    } 

    public void delete() {
        if (XDialog.confirm("Bạn thực sự muốn xóa?")) {
            this.fillToTable();

        }else {
            XDialog.alertError("Xóa thất bại");
        }
    }

    public void edit() {
        Promotion entity = items.get(tblPromotion.getSelectedRow());
        this.setForm(entity);
        this.setEditable(true);
        tabs.setSelectedIndex(1);
    }

    public void setEditable(boolean editable) {
        txtId.setEnabled(!editable);
        btnCreate.setEnabled(!editable);
        btnUpdate.setEnabled(editable);
        btnDelete.setEnabled(editable);
        btnClear.setEnabled(false);

    }

    public void clearForm() {
    txtName.setText("");
    txtStartDate.setText("");
    txtEndDate.setText("");
    txtDiscount.setText("");
    Date now = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat(pattern);
    txtStartDate.setText(sdf.format(now));
    txtBegin.setText(sdf.format(now));
    txtEnd.setText(sdf.format(now));
    tblPromotion.setRowSorter(null); // Xóa bộ lọc
    tblPromotion.clearSelection();
}

    public void deleteCheckedItems() {
        if (XDialog.confirm("Bạn thực sự muốn xóa các mục chọn?")) {
            for (int i = 0; i < tblPromotion.getRowCount(); i++) {
                if (Boolean.TRUE.equals(tblPromotion.getValueAt(i, 5))) {
                    dao.deleteById(items.get(i).getId());
                }
            }
            this.fillToTable();
        }
    }
    
    public void checkAll(boolean isChecked) {
    DefaultTableModel model = (DefaultTableModel) tblPromotion.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        model.setValueAt(true, i, 5); // Cột 5 là checkbox
    }
}
    public void UncheckAll(boolean isChecked) {
    DefaultTableModel model = (DefaultTableModel) tblPromotion.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        model.setValueAt(false, i, 5); // Cột 5 là checkbox
    }
}
    

}
